name: Vispro  # Environment name
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  # Specify the Python version you’re using
  - numpy>=1.18.0
  - pytorch>=1.7.0
  - torchvision>=0.8.0
  - scikit-image>=0.16.2
  - pillow>=7.0.0
  - scipy>=1.4.1
  - matplotlib>=3.1.3
  - pymatting>=1.1.5
  - kornia>=0.5.0

